DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS resumes CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE resumes (
  id SERIAL PRIMARY KEY NOT NULL,
  resumedata JSONB NOT NULL default '{}',
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
